global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'Alertmanager'

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scheme: https
    basic_auth:
      username: admin
      password: admin
    params:
      backbase.basic-authentication.username: ['admin']
      backbase.basic-authentication.password: ['admin']
    static_configs:
    - targets: ['SERVER_URL']